//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApproccioDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public string Iban { get; set; }
        public int BankAccountNumber { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
    }
}
